<?php
/**
 * @title            Japanese Language File
 *
 * @author           kirakira-nana <seniorninja652@gmail.com>
 * @copyright        (c) 2020, kirakira-nana.
 * @license          MIT License; See LICENSE.md and COPYRIGHT.md in the root directory.
 * @package          PH7 / Lang / JA
 */

namespace PH7;

$LANG = [
    'lang' => 'ja',
    'charset' => 'utf-8',
    'lang_name' => '日本語',
    'version' => 'バージョン',
    'CMS_desc' => '<p>' . Controller::SOFTWARE_NAME . ' インストーラーへようこそ。<br />
        <strong>pH7Builder</strong> をお選びいただき、ありがとうございます。</p>',
    'choose_install_lang' => 'インストールを始める言語を選んでください',
    'requirements_desc' => 'インストーラーが PHP の要件を確認しました。<a href="' . Controller::SOFTWARE_REQUIREMENTS_URL . '" target="_blank" rel="noopener">サーバー要件の詳細</a>もご確認ください。',
    'requirements2_desc' => '続ける前に MySQL データベースを作成し、全権限を持つユーザーを割り当ててください。データベース名、ユーザー名、パスワードを手元に用意してください。',
    'config_path' => '&quot;protected&quot; フォルダーのパス',
    'desc_config_path' => '&quot;protected&quot; フォルダーのフルパスを指定してください。<br />
        セキュリティのため、ホスティング環境が許す場合は公開ディレクトリの外に置いてください。',
    'need_frame' => 'インラインフレームに対応したウェブブラウザーを使用してください。',
    'path_protected' => '&quot;protected&quot; フォルダーのパス',
    'next' => '次へ',
    'go' => '次のステップ =>',
    'later' => '今はしない',
    'license_agreements' => 'ライセンスと同意事項',
    'license_agreements_desc' => 'インストールを続ける前に、ライセンスと同意事項をよく読み、同意してください。',
    'register' => '保存する',
    'site_name' => 'サイト名',
    'agree_license' => '上記の利用条件を<strong>読み</strong>、<strong>同意</strong>します。',
    'conform_to_laws' => '私は、<strong>自分、自社、ウェブサイトおよび利用者に適用される法令を常に遵守し、サイトを適法に運営すること</strong>に同意し、<a href="https://github.com/pH7Software/pH7-Social-Dating-CMS/blob/18.x/docs/LAUNCH_CHECKLIST.md#legal-and-privacy" target="_blank" rel="noopener">「利用規約」「プライバシーポリシー」（および必要な法的ページ）を更新</a>して適用法令に完全に従うことに同意します。',
    'responsibilities_agreement' => '私は<strong>自己の責任で本ソフトウェアを使用すること</strong>に同意し、本ソフトウェアの使用または使用不能から生じる直接・間接の損害を含め、いかなる損害についても作者は責任を負わないことに同意します。',
    'step' => 'ステップ',
    'welcome' => 'インストールへようこそ',
    'welcome_to_installer' => 'インストール',
    'config_site' => 'ウェブサイトを設定する',
    'config_system' => 'データベース / システム設定',
    'finish' => '完了しました。pH7Builder のインストールが終わりました。',
    'go_your_site' => '新しいサイトへ進む',
    'go_your_admin_panel' => '管理画面へ進む',
    'error_page_not_found' => 'ページが見つかりません',
    'error_page_not_found_desc' => 'お探しのページは見つかりませんでした。',
    'no_protected_exist' => '&quot;protected&quot; ディレクトリが見つかりません。',
    'no_protected_readable' => '&quot;protected&quot; ディレクトリの権限を読み取り可能（CHMOD 755）に変更してください。',
    'stale_constants_recovery' => '以前設定した protected ディレクトリは利用できません。正しいパスを選んでください。インストーラーは古い _constants.php を安全に置き換えます。',
    'no_public_writable' => 'ウェブサーバーユーザーがルートディレクトリに書き込めません。一時的に所有者/グループの書き込み権限を付与してください。全員書き込み可能な権限は使わないでください。',
    'no_app_config_writable' => 'ウェブサーバーユーザーが protected/app/configs に書き込めません。一時的に所有者/グループの書き込み権限を付与してください。全員書き込み可能な権限は使わないでください。',
    'runtime_path_not_writable' => 'ウェブサーバーユーザーが %s に書き込めません。所有者/グループの書き込み権限を付与してください。全員書き込み可能な権限は使わないでください。',
    'database_error' => 'データベース操作に失敗しました。ホスト名、ポート、データベース名、認証情報、権限を確認してください。技術詳細はインストーラーログに記録されています。',
    'initial_admin_mismatch' => 'このデータベースには既に管理者がいますが、入力したログイン情報と一致しません。元の管理者メール、ユーザー名、パスワードで再試行するか、テーブルを空にしてからやり直してください。',
    'error_sql_import' => 'データベーススキーマをインポートできませんでした。空のデータベースを使い、再試行前に _install/data/logs/php_error.log を確認してください。',
    'require_mysql_version' => '続行するには MySQL ' . PH7_REQUIRED_SQL_VERSION . ' 以上が必要です。',
    'field_required' => 'この項目は必須です',
    'all_fields_mandatory' => 'アスタリスク（*）の付いた項目はすべて必須です',
    'db_hostname' => 'データベースサーバーのホスト名',
    'desc_db_hostname' => '通常は &quot;localhost&quot; または &quot;127.0.0.1&quot;',
    'db_name' => 'データベース名',
    'db_username' => 'データベースのユーザー名',
    'db_password' => 'データベースのパスワード',
    'db_prefix' => 'テーブル名の接頭辞',
    'desc_db_prefix' => '同じデータベースに複数の pH7Builder を入れる場合に便利です。
        セキュリティのため、初期値の変更もおすすめします。',
    'db_encoding' => '文字コード',
    'desc_db_encoding' => 'データベースの文字コードです。絵文字を含む国際化には utf8mb4 のままにしてください。',
    'db_port' => 'データベースのポート番号',
    'desc_db_port' => '不明な場合は "3306" のままにしてください。',
    'ffmpeg_path' => 'FFmpeg 実行ファイルのパス（不明な場合はホスティング会社に確認してください）',
    'ffmpeg_optional' => '任意です。FFmpeg がない場合は空のままにしてください。ローカル動画変換は利用できません。',
    'bug_report_email' => 'バグ報告用メールアドレス',
    'bug_report_email_placeholder' => 'error_log@yourdomain.com',
    'admin_first_name' => '名',
    'admin_last_name' => '姓',
    'admin_username' => 'ユーザー名（管理画面ログイン用）',
    'admin_login_email' => '管理画面ログイン用メールアドレス',
    'admin_email' => '管理者メールアドレス',
    'admin_email_placeholder' => 'admin@yoursite.com',
    'admin_feedback_email' => 'お問い合わせフォーム用メールアドレス',
    'admin_feedback_email_placeholder' => 'feedback@yoursite.com',
    'admin_return_email' => '送信専用メールアドレス（通常は noreply@yoursite.com）',
    'admin_return_email_placeholder' => 'noreply@yoursite.com',
    'admin_password' => 'パスワード（管理画面ログイン用）',
    'admin_passwords' => 'パスワードの確認',
    'bad_site_name' => 'サイト名は 2〜50 文字で入力してください。',
    'bad_email' => 'メールアドレスが正しくありません',
    'bad_username' => 'ユーザー名が正しくありません',
    'username_too_short' => 'ユーザー名が短すぎます。3 文字以上にしてください',
    'username_too_long' => 'ユーザー名が長すぎます。最大 30 文字です',
    'password_no_number' => 'パスワードには数字を 1 文字以上含めてください',
    'password_no_upper' => 'パスワードには英大文字を 1 文字以上含めてください',
    'password_too_short' => 'パスワードが短すぎます。12 文字以上にしてください。',
    'password_too_long' => 'パスワードが長すぎます',
    'passwords_different' => '確認用パスワードが一致しません',
    'bad_first_name' => '名を入力してください。2〜20 文字である必要があります。',
    'bad_last_name' => '姓を入力してください。2〜20 文字である必要があります。',
    'insecure_password' => 'セキュリティのため、パスワードはユーザー名・名・姓と異なるものにしてください。',
    'remove_install_folder' => 'セキュリティのため、サイトを使う前にサーバーから &quot;_install&quot; フォルダーを削除してください。',
    'remove_install_folder_auto' => '&quot;install&quot; ディレクトリを自動削除する（削除権限が必要です）。',
    'confirm_remove_install_folder_auto' => '警告: /_install/ フォルダー内のすべてのファイルが削除されます。',
    'title_email_finish_install' => 'インストール完了のお知らせ',
    'content_email_finish_install' => '<p><strong>pH7Builder サイトのインストールが完了しました。</strong></p>
        <p>サイト: <a href="' . PH7_URL_ROOT . '">' . PH7_URL_ROOT . '</a></p>
        <p>管理画面: <a href="' . PH7_URL_ROOT . PH7_ADMIN_MOD . '">' . PH7_URL_ROOT . PH7_ADMIN_MOD . '</a><br />
            ログインメール: <em>' . (!empty($_SESSION['val']['admin_login_email']) ? escape($_SESSION['val']['admin_login_email']) : '') . '</em><br />
            ユーザー名: <em>' . (!empty($_SESSION['val']['admin_username']) ? escape($_SESSION['val']['admin_username']) : '') . '</em><br />
            パスワード: <em>非表示。インストール時に設定したパスワードを使用してください。</em>
        </p>
        <p>インストーラーディレクトリを削除したうえで、<a href="' . Controller::SOFTWARE_LOCKDOWN_URL . '">本番ロックダウンコマンドを実行</a>してからログインしてください。本番で会員や決済を受け付ける前にローンチチェックリストを完了してください。</p>
        <p>ドキュメントと問題報告: <a href="' . Controller::SOFTWARE_GIT_REPO_URL . '">GitHub の pH7Builder</a>。</p>
        <p>よろしくお願いいたします。<br /><strong><a href="' . Controller::AUTHOR_URL . '">Pierre-Henry Soria</a></strong><br />pH7Builder 創作者</p>',
    'yes_dir' => 'ディレクトリが見つかりました。',
    'no_dir' => 'ディレクトリが存在しません。',
    'wait_importing_database' => 'データベースをインポートしています。しばらくお待ちください。<br />
        数分かかることがあります。',
    'add_sample_data' => 'ローカル評価用のサンプルプロフィールを生成する（本番前に削除してください）',
    'niche' => '作りたいコミュニティの種類を選んでください',
    'social_dating_niche' => 'ソーシャル出会い',
    'social_niche' => 'コミュニティ',
    'dating_niche' => '出会い・マッチング',
    'base_niche_desc' => 'この種類を選ぶと、主要モジュールが有効になり、汎用テンプレート（ソーシャル出会いテーマ）が初期選択されます。',
    'zendate_niche_desc' => 'コミュニティを選ぶと、ソーシャル系モジュールのみが有効になり、プロフィール写真は初期状態では必須ではなく、ソーシャルテーマが選ばれます。',
    'datelove_niche_desc' => '出会い・マッチングを選ぶと、出会い系モジュールのみが有効になり、プロフィール写真が初期状態で必須になり、出会いテーマが初期テーマになります。',
    'go_social_dating' => 'ソーシャル出会いで進む',
    'go_social' => 'コミュニティで進む',
    'go_dating' => '出会いで進む',
    'recommended' => 'おすすめ',
    'recommended_desc' => 'まだ迷っている場合は、この種類を選んでください。',
    'note_able_to_change_niche_settings_later' => 'テンプレートの変更やモジュールの有効/無効は、あとから管理画面で変更できます。',
    'will_you_make_donation' => 'ソフトウェアの維持と改善にご協力いただけますか？',
    'donate_here' => 'パトロンとして購読する',
    'or_paypal_donation' => '<span class="underline">PayPal</span> からも支援できます',
    'warning_no_js' => 'ブラウザーで JavaScript が無効です。<br />
        このサイトを使うには、ブラウザーの設定で JavaScript を有効にしてください。',
    'admin_url' => '管理画面 URL',
    'next_steps' => '次の手順: インストーラーを削除し、ログイン前に <a href="' . Controller::SOFTWARE_LOCKDOWN_URL . '" target="_blank" rel="noopener">本番ロックダウンコマンドを実行</a>してください。その後、管理画面の開始チェックリストがブランディングと公開作業を案内します。',
    'powered' => '提供',
    'loading' => '読み込み中...',
    'invalid_action' => 'このインストーラーフォームの有効期限が切れたか、別のセッションで開かれました。ページを再読み込みしてやり直してください。',
    'install_access_intro' => 'サーバーで作成した一度限りのインストーラーアクセストークンを入力してください。他の人が最初の管理者アカウントを取得するのを防ぎます。',
    'install_access_not_configured' => 'インストーラーへのアクセスはロックされています。pH7Builder ディレクトリで次のコマンドを実行し、このページを再読み込みしてください。',
    'install_access_token' => 'インストーラーアクセストークン',
    'install_access_invalid' => 'インストーラーアクセストークンが正しくありません。',
    'invalid_database_settings' => '有効なデータベースホスト、ポート（1〜65535）、名前、ユーザー名、テーブル接頭辞を入力してください。文字コードは utf8mb4 である必要があります。',
    'invalid_ffmpeg_path' => 'FFmpeg のパスは実行ファイルではありません。修正するか、空にしてください。',
    'invalid_niche' => '利用可能なサイト種類から 1 つ選んで、やり直してください。',
    'sample_data_warning' => 'サイトはインストールされましたが、サンプルプロフィールの生成が完了しませんでした。インストーラーログを確認し、本番前に生成されたサンプルを削除してください。',
    'welcome_email_warning' => 'サイトはインストールされましたが、歓迎メールを送信できませんでした。公開前に管理画面でメール配信を設定してください。',
    'remove_install_failed' => 'インストーラーディレクトリを完全に削除できませんでした。サイトを開く前に _install を手動で削除してください。',
];
