; テーマ情報
[theme.information]
name = "Cartoon"
type = "カラフルなカートゥーンテーマ"
category = "ソーシャル"
version = "1.0.0"
preview_img = "img/preview.png"
author = "kirakira-nana"
license = "MIT"
website = "https://github.com/kirakira-nana"
email = "seniorninja652@gmail.com"
